name: Build

on:
  push:
    branches:
      - main
      - 4-setup-cicd
  pull_request:
    branches:
      - main

jobs:
  build-linux-x86-64:
    name: Linux x86-64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo wget https://github.com/PLAST-software/plast-library/releases/download/v2.3.2/plastbinary_linux_v2.3.2.tar.gz
          sudo apt-get update
          sudo apt-get install -y tar
        continue-on-error: false

      - name: Set up PLAST binaries
        run: |
          tar -zxf plastbinary_linux_v2.3.2.tar.gz
          echo "PLAST_BINARIES_DIR=$GITHUB_WORKSPACE/plastbinary_linux_v2.3.2/build/bin" >> $GITHUB_ENV
          echo "$PLAST_BINARIES_DIR" >> $GITHUB_PATH
          echo "PLAST binaries added to PATH."
        continue-on-error: false

      - name: Verify PLAST installation
        run: |
          plast -h || { echo 'PLAST installation failed'; exit 1; }

      - name: Clone acc2tax repository
        run: |
          git clone https://github.com/richardmleggett/acc2tax.git

      - name: Build acc2tax
        run: |
          cd acc2tax
          gcc -o acc2tax acc2tax.c

      - name: Verify acc2tax build
        run: |
          cd acc2tax
          ./acc2tax --help || { echo 'acc2tax build failed'; exit 1; }