name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-linux-x86-64:
    name: Linux x86-64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: eukfinder
          auto-update-conda: true
          environment-file: eukfinder_env.yml
          cache-builds: true

      - name: Install dependencies
        run: |
          sudo wget https://github.com/PLAST-software/plast-library/releases/download/v2.3.2/plastbinary_linux_v2.3.2.tar.gz
          sudo apt-get update
          sudo apt-get install -y tar

      - name: Setup PLAST binaries
        run: |
          tar -zxf plastbinary_linux_v2.3.2.tar.gz

      - name: Verify PLAST installation
        run: |
          export PATH=$PWD/plastbinary_linux_v2.3.2/build/bin:$PATH
          plast -h || { echo 'PLAST installation failed'; exit 1; }

      - name: Clone acc2tax repository
        run: |
          git clone https://github.com/richardmleggett/acc2tax.git

      - name: Build acc2tax
        run: |
          cd acc2tax
          gcc -o acc2tax acc2tax.c

      - name: Verify acc2tax build
        run: |
          cd acc2tax
          ./acc2tax --help || { echo 'acc2tax build failed'; exit 1; }

      - name: Verify eukfinder sub-calls
        run: |
          ls -l
          cd bin/
          ls -l
          alias Eukfinder='python Eukfinder.py'
          Eukfinder read_prep -h
          Eukfinder short_seqs -h
          Eukfinder long_seqs -h
          
